# Generated by Django 5.1.7 on 2025-04-25 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_cart_options_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Cart', 'verbose_name_plural': 'Carts'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['-added_at'], 'verbose_name': 'Product in cart', 'verbose_name_plural': 'Products in cart'},
        ),
    ]
